{
 "title": "Server LAB",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_exporter_build_info, job)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_exporter_build_info{job=~\"$job\"}, instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(node_exporter_build_info{instance=~\"$node:(.*)\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Basic Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Core",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node:$port\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$node:$port\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Total Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_network_speed_bytes{instance=\"172.27.100.154:9100\", job=\"lab04\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$node:$port\",job=~\"$job\"} - node_boot_time_seconds{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  { "title": "Basic Gauge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:$port\",job=~\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"$node:$port\",job=\"$job\"}-node_memory_MemAvailable_bytes{instance=\"$node:$port\",job=\"$job\"})/node_memory_MemTotal_bytes{instance=\"$node:$port\",job=\"$job\"} * 100"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node:$port\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node:$port\",job=\"$job\"}) / node_memory_SwapTotal_bytes{instance=\"$node:$port\",job=\"$job\"} * 100"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=\"$node:$port\",job=\"$job\", mountpoint=\"/\", fstype=\"xfs\"} - node_filesystem_free_bytes{instance=\"$node:$port\",job=\"$job\", mountpoint=\"/\", fstype=\"xfs\"})/node_filesystem_size_bytes{instance=\"$node:$port\",job=\"$job\", mountpoint=\"/\", fstype=\"xfs\"} *100"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$node:$port\",job=~\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU System Load (5m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load5{instance=~\"$node:$port\",job=~\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  { "title": "Jenkins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Pipeline Total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "quanpc_job_total{instance=\"172.27.100.223:15020\",job=\"quanpc\"}"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "quanpc_cluster_member{instance=\"172.27.100.223:15020\",job=\"quanpc\"}"
    }
   ]
  },
  {
   "title": "Online Nodes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "quanpc_cluster_statusMember{instance=\"172.27.100.223:15020\",job=\"quanpc\", status=\"on\"}"
    }
   ]
  },
  {
   "title": "Offline Nodes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "quanpc_cluster_statusMember{instance=\"172.27.100.223:15020\",job=\"quanpc\", status=\"off\"}"
    }
   ]
  },
  {
   "title": "Total Builds",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "quanpc_job_pipe_total_build{}" },
    { "expr": "quanpc_job_repeated_failure{}" }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic Basic",
     "type": "graph",
     "description": "Basic network info per interface",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "recv {{device}}"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "trans {{device}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Used",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "bytes", "label": "Byte" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=~\"$node:$port\",job=~\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=~\"$node:$port\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
       "legendFormat": "{{device}} - Reads completed"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=~\"$node:$port\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
       "legendFormat": "{{device}} - Writes completed"
      }
     ]
    },
    {
     "title": "I/O Usage Times",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "ms", "label": "Tổng thời gian IO" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node:$port\",job=~\"$job\",device=~\"[a-z]*[a-z]\"} [5m])",
       "legendFormat": "{{device}} -Thời gian I/Os"
      }
     ]
    },
    {
     "title": "I/O Usage Read/Write",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=~\"$node:$port\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
       "legendFormat": "{{device}} -Read bytes thành công"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=~\"$node:$port\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
       "legendFormat": "{{device}} -Write bytes thành công"
      }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "RAM Distributton",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_memory_MemFree_bytes{instance=\"$node:$port\",job=\"$job\"}/node_memory_MemTotal_bytes{instance=\"$node:$port\",job=\"$job\"}*100",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"$node:$port\",job=\"$job\"}/node_memory_MemTotal_bytes{instance=\"$node:$port\",job=\"$job\"}*100",
       "legendFormat": "Cache"
      },
      {
       "expr": "node_memory_Buffers_bytes{instance=\"$node:$port\",job=\"$job\"}/node_memory_MemTotal_bytes{instance=\"$node:$port\",job=\"$job\"}*100",
       "legendFormat": "Buffer"
      },
      {
       "expr": "(node_memory_MemTotal_bytes{instance=\"$node:$port\",job=\"$job\"}-node_memory_MemAvailable_bytes)/node_memory_MemTotal_bytes{instance=\"$node:$port\",job=\"$job\"}*100",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Memory Stack",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_MemFree_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_Buffers_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_Cached_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_Slab_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_PageTables_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_SwapCached_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Apps - RAM được sử dụng bởi người dùng"
      },
      {
       "expr": "node_memory_PageTables_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "PageTables - RAM được sử dụng để  Virtual và Physical "
      },
      {
       "expr": "node_memory_SwapCached_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
      },
      {
       "expr": "node_memory_Slab_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Cache - Parked file data (file content) cache"
      },
      {
       "expr": "node_memory_Buffers_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Unused - Free memory unasigned"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$node:$port\",job=~\"$job\"})",
       "legendFormat": "Swap - Swap space used"
      },
      {
       "expr": "node_memory_HardwareCorrupted_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Harware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Used",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "CPU đã sử dụng" }
     ],
     "targets": [
      {
       "expr": "((count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:$port\",job=~\"$job\"}[$__interval]))))*100",
       "legendFormat": "CPU Used"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "ms", "label": "Tỉ lệ phần trăm" }
     ],
     "targets": [
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "System - Xủ lý kernel mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='user',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "User - Thời gian dành cho người dùng"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='nice',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Nice - Thực thi ưu tiên trong User mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Idle - Thời gian rảnh"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Iowait - Thời gian đợi I/O"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='irq',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Irq - Thời gian phục vụ bị gián đoạn"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='softirq',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Softirq - Thời gian phục vụ bị gián đoạn"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='steal',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Steal - Thời gian dành cho máy ảo"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='guest',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Guest - Thời gian chạy chế độ khách"
      }
     ]
    }
   ]
  },
  {
   "title": "AlertManager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Instance Down",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "ALERTS{alertname=\"InstanceDown\"}",
       "labelSelector": "*",
       "legendFormat": "{{ msg }}",
       "target": "Query",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Full Disk",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "alertname=\"DiskFull\", df=\"opt\"",
       "labelSelector": "*",
       "legendFormat": "{{ msg }}",
       "target": "Query",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "MemoryFree75%",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "ALERTS{alertname=\"MemoryFree85%\"}",
       "labelSelector": "*",
       "target": "Query",
       "type": "single"
      }
     ]
    },
    {
     "title": "NodeMemoryUsage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "alertname=\"NodeMemoryUsage\"",
       "labelSelector": "*",
       "target": "Query",
       "type": "single"
      }
     ]
    },
    {
     "title": "MemoryFree75%",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "ALERTS{alertname=\"MemoryFree85%\"}",
       "labelSelector": "*",
       "legendFormat": "{{ job }}",
       "target": "Query",
       "type": "table"
      }
     ]
    }
   ]
  }
 ]
}